"use client";

import { useEffect, useState } from "react";

export default function AdminBusinessTools() {
  const [customers, setCustomers] = useState<{ id: string; full_name: string; email: string; order_count: number }[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/admin/customers").then((response) => response.json()).then((data) => setCustomers(data.customers ?? [])); }, []);
  async function submitPromo(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/admin/promos", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, discountPercent: Number(data.discountPercent) || null, minimumOrder: Number(data.minimumOrder) || 0 }) }); setMessage(response.ok ? "Promo code created." : "Could not create promo code."); if (response.ok) event.currentTarget.reset(); }
  async function submitCategory(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/admin/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); setMessage(response.ok ? "Category created." : "Could not create category."); if (response.ok) event.currentTarget.reset(); }
  return <section className="mt-8 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-neutral-200 p-6"><h2 className="font-bold">Promotions</h2><form onSubmit={submitPromo} className="mt-4 grid gap-2 sm:grid-cols-2"><input name="code" required placeholder="Code e.g. WELCOME10" className="rounded-lg border border-neutral-300 px-3 py-2" /><input name="discountPercent" type="number" min="1" max="100" placeholder="Discount %" className="rounded-lg border border-neutral-300 px-3 py-2" /><input name="minimumOrder" type="number" min="0" placeholder="Minimum order" className="rounded-lg border border-neutral-300 px-3 py-2" /><button className="rounded-lg bg-brand px-3 py-2 font-semibold text-white">Create promo</button></form><form onSubmit={submitCategory} className="mt-6 grid gap-2 sm:grid-cols-2"><input name="name" required placeholder="Category name" className="rounded-lg border border-neutral-300 px-3 py-2" /><input name="slug" required placeholder="category-slug" className="rounded-lg border border-neutral-300 px-3 py-2" /><input name="icon" placeholder="Icon" className="rounded-lg border border-neutral-300 px-3 py-2" /><button className="rounded-lg border border-black px-3 py-2 font-semibold">Add category</button></form>{message && <p className="mt-3 text-sm text-brand-dark">{message}</p>}</div><div className="rounded-2xl border border-neutral-200 p-6"><h2 className="font-bold">Customers</h2><div className="mt-4 space-y-3">{customers.slice(0, 8).map((customer) => <div key={customer.id} className="border-b border-neutral-100 pb-2"><p className="font-semibold">{customer.full_name}</p><p className="text-sm text-neutral-500">{customer.email} · {customer.order_count} orders</p></div>)}{customers.length === 0 && <p className="text-sm text-neutral-500">No customer accounts yet.</p>}</div></div></section>;
}
